apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: webserver-app
  namespace: webserver-acm2
spec:
  type: Git
  pathname: https://github.com/michaelkotelnikov/rhacm-workshop.git
