apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: aws-clusters
  namespace: bank-color
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: eks
      location: cloud