apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: aws-clusters
  namespace: aws-acm
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      env: eks
