apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: aws-app-dev
  namespace: aws-acm
  labels:
    app: aws-app
  annotations:
    apps.open-cluster-management.io/github-path: aws-deploy
    apps.open-cluster-management.io/git-branch: master
spec:
  channel: aws-acm/aws-app
  placement:
    placementRef:
      kind: PlacementRule
      name: aws-clusters
